### ISSUE TITLE
An error occurred processing input. Please check input

### ISSUE THREAD

**Issue by riramar** [secdec/attack-surface-detector-burp#1]
I'm trying to import endpoints from a ruby on rails source code base but when I select the folder and click on "Import Endpoints from the Source" I'm getting the error message "An error occurred processing input. Please check input". I'm not able to see any errors from the extension error logs.
Any clue what's wrong? Is there a debug mode?
Thanks!

**Comment by matthewD-AVI** [comment]
Hello @riramar  I apologize for the delay. I will have to look into this issue as it seems there is an error processing the your webapp. There is currently no debug mode though running Burp with from the command line may help see what the specific error is. May I ask what application you are testing? Is it open source so that I can download and investigate the error as well?

-Matthew

**Comment by matthewD-AVI** [comment]
@riramar  Here is a link to a dummy RoR application that I tested and know works. If you run Burp in command line I would be interested to see the specific errors so I can resolve any issues that are needed on our end

https://github.com/OWASP/railsgoat/releases

**Comment by riramar** [comment]
just to let you @matthewD-AVI know the import from railsgoat works perfectly. I'll run burp manually to check the logs from command line.

**Comment by matthewD-AVI** [comment]
@mAshraf9 Are you trying to process Ruby on rails as well? Is the source to your application open source so I can test it myself and see the error messages? Are you using the latest version of teh ASD technology through the BAap store or located here(https://github.com/secdec/attack-surface-detector-burp/releases/tag/1.1.2)? Have you tried launching Burp from the command line and then trying to import your endpoints and if so what was the error?

**Comment by riramar** [comment]
Got he problem.

```
INFO [AWT-EventQueue-0] RailsFrameworkChecker.check(69) | Got 169 *.rb files from the directory.
INFO [AWT-EventQueue-0] RailsFrameworkChecker.check(70) | .../config/routes.rb was found.
```

The extension is not able to dynamic find the routes.rb file.

**Comment by tylercamp** [comment]
@riramar Is `/config/routes.rb` not the location of your routes file? (Relative to your project directory)

**Comment by riramar** [comment]
Yes, the file is in the right place but the 169 *.rb files are in different folders.

**Comment by tylercamp** [comment]
@riramar Can you go into more detail on what you mean by "not able to dynamic find the routes.rb file"? It looks like the plugin was able to find your `routes.rb` successfully. Are those 169 *.rb files all in the project being scanned, or in different projects entirely?

Is there any other error information available after running Burp from command-line with the plugin? So far there isn't enough information for us to start debugging the issue.

**Comment by lightos** [comment]
I am currently having the same issue with a RoR application which src-code is private. Here is the console output:

**Comment by tylercamp** [comment]
Several rails parsing issues have been found and are being addressed, though we can't confirm whether these changes will affect the issues that you two are having. These fixes should be available by the end of today or, at the latest, end of tomorrow.

**Comment by tylercamp** [comment]
@riramar @lightos @mAshraf9 Can you tell us what version of Rails you are using?

**Comment by lightos** [comment]
Thanks, I look forward to testing the fixes when they are released.

The application is using:
gem 'rails', '~> 5.0.7'

**Comment by riramar** [comment]
Rails Version 5.2.0

**Comment by matthewD-AVI** [comment]
@riramar  @lightos  @mAshraf9 The rails parsing issues that @tylercamp was talking about is now avaliable in both the Burp and Zap Plugins. You can download the binary here: https://github.com/secdec/attack-surface-detector-burp/releases/tag/1.1.2
